- hosts: localhost
  roles:
    - role: add-fileserver
      fileserver: "{{ site_logs }}"
    - role: ara-report

- hosts: "{{ site_logs.fqdn }}"
  gather_facts: false
  roles:
    - role: upload-logs
      zuul_log_url: http://80.158.7.84/logs/windmill
      zuul_logserver_root: "{{ site_logs.path }}"
